back/urls.py
from django.urls import path
from . import views

app_name = 'back'

urlpatterns = [
    path('', views.index, name='index'),
    path('success', views.post_data, name='success')
]

interview_task/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('back.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/models.py
from pickle import FALSE
from django.db import models
from django.contrib.auth.models import User


class MyUser(User):
    def __str__(self) -> str:
        return self.username

class Task(models.Model):
    userId = models.IntegerField()
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    body = models.CharField(max_length=255)

back/forms.py
from django.forms import ModelForm
from .models import MyUser
from django.utils.translation import gettext_lazy as _
from django import forms

class MyUserForm(ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'password']
        labels = {
            'username': _('Username'),
            'password': _('Password')
                    }
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'password': forms.PasswordInput(attrs={'class':'form-control'})
        }

back/views.py
from django.shortcuts import render
from .forms import MyUserForm
import requests
from back.models import Task


# Create your views here.
def index(request):
    context = {
    }
    return render(request, 'back/index.html', context)

def post_data(request):
    if request.method == 'POST':
        api_url = 'http://jsonplaceholder.typicode.com/posts'
        try:
            response = requests.post(api_url)
            print(response.json())
            idval = ''
            if 'id' in response.json():
                idval = response.json()['id']
            title = ''
            if 'title' in response.json():
                title = response.json()['title']
            bd = ''
            if 'body' in response.json():
                bd = response.json()['body']
            userId = 0
            if 'userId' in response.json():
                userId = response.json()['userId']
            new_db = Task(id=idval, title=title, body=bd, userId=userId)
        except Exception as e:
            print("error")
        user_form = MyUserForm()
        context = {
            'success': '1',
            'id': idval,
            'title': title,
            'body': bd,
            'userId': userId
        }
        return render(request, 'back/success.html', context)
    else:
        user_form = MyUserForm()
        context = {
            'success': '0'
        }
        return render(request, 'back/index.html', context)

back/templates/back/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <!-- ================== BEGIN core-css ================== -->
    <link href="{% static 'css/vendor/vendor.min.css' %} " rel="stylesheet" type="text/css" />
    <link href="{% static 'css/vendor/app.min.css' %}" rel="stylesheet" />
    <!-- ================== END core-css ================== -->

</head>

<body class='pace-top'>
    <div id="app" class="app app-full-height app-without-header">
		<div class="login">
			<div class="login-content">
				<form action="{% url 'back:success' %}" method="POST" name="login_form">
                    {% csrf_token %}
					<h1 class="text-center">Fetch Data</h1>
					<div class="mb-3"></div>
					<button type="submit" class="btn btn-outline-theme btn-lg d-block w-100 fw-500 mb-3">Submit</button>
				</form>
			</div>
		</div>
	</div>
    <!-- ================== BEGIN core-js ================== -->
    <script src="{% static 'js/vendor/vendor.min.js' %}"></script>
    <script src="{% static 'js/vendor/app.min.js' %}"></script>
    <!-- ================== END core-js ================== -->
</body>

</html>

back/templates/back/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <!-- ================== BEGIN core-css ================== -->
    <link href="{% static 'css/vendor/vendor.min.css' %} " rel="stylesheet" type="text/css" />
    <link href="{% static 'css/vendor/app.min.css' %}" rel="stylesheet" />
    <!-- ================== END core-css ================== -->

</head>

<body class='pace-top'>
    <div id="app" class="app app-full-height app-without-header">
		<div class="login">
			<div class="login-content">
                    <h1>Success</h1>
					<h1 class="text-center">Result Data</h1>
					<div class="mb-3"></div>
                    <h3>ID: {{id}}</h3>
                    <h3>Title: {{title}}</h3>
                    <h3>Body: {{body}}</h3>
                    <h3>UserID: {{userId}}</h3>

				</form>
			</div>
		</div>
	</div>
    <!-- ================== BEGIN core-js ================== -->
    <script src="{% static 'js/vendor/vendor.min.js' %}"></script>
    <script src="{% static 'js/vendor/app.min.js' %}"></script>
    <!-- ================== END core-js ================== -->
</body>

</html>